### ISSUE TITLE
Has it been released in any tinfoil shop yet?

### ISSUE THREAD

**Issue by CortexBonus** [D-Official/PizzaTowerSwitch-FMOD#1]
I've been looking for any free functional tinfoil shops and so far I have yet to encounter one that has pizza tower's sr4 update.

**Comment by D-Official** [comment]
SR 4 is available on GratiSwitch, which is free. You can find the shop link on the subreddit with the same name.
(I might release encrypted bins on this repository soon... a lot of people are struggling to find the update unfortunately)

**Comment by Dededeez** [comment]
I don't believe it is on GratiSwitch actually, I checked it and I still see SR 3 as the only one on it

**Comment by D-Official** [comment]
> I don't believe it is on GratiSwitch actually, I checked it and I still see SR 3 as the only one on it

You are most likely correct, my mistake. looks like it found my local SR 4 NSP and installed that. Will most likely start uploading the encrypted bins if it's not on there.

**Comment by CortexBonus** [comment]
Yeah so I looked it up in GratiSwitch and no sign of sr4 only sr3 is available there.

**Comment by D-Official** [comment]
Please see the releases tab :D
