### ISSUE TITLE
Add transparent palette as a modded palette

### ISSUE THREAD

**Issue by ERWANDAWA** [D-Official/PizzaTowerSwitch-FMOD#10]
In the modded palette on the port menu

**Comment by D-Official** [comment]
this will be considered when the port needs to be updated again (to fix a game-breaking bug, or to update the Pizza Tower version)

**Comment by lennytm** [comment]
you can do this yourself in the meanwhile just by modifying spr_peppallette, just pick one and turn the colors transparent

**Comment by lennytm** [comment]
i cant help with adding more palletes to that file tho

**Comment by lucasdaweb95** [comment]
> you can do this yourself in the meanwhile just by modifying spr_peppallette, just pick one and turn the colors transparent

or edit your save to have an invalid pallette
