### ISSUE TITLE
can i port saves?

### ISSUE THREAD

**Issue by lennytm** [D-Official/PizzaTowerSwitch-FMOD#11]
i really want to port my save so i dont have to do everything again, is there a way to do it yet?

**Comment by D-Official** [comment]
There is! If you use any save dumping app and navigate to where it stores them on your Switch's SD card, you will find the exact same save structure. You should be able to drop your PC save in there and reload the save using the same save dumping app.

**Comment by lennytm** [comment]
that worked! thanks alot.


erhm, another concern, is there a way to mod audio? i modified the audio in the data.win but theres no sound in game, how do i fix that?

**Comment by D-Official** [comment]
If you modify the sound files in the game.win then the changes should appear in game. What are you trying to modify exactly? Are you sure the game is actually using your new .win file?

**Comment by lennytm** [comment]
yeap, because only the songs i modified are muted

**Comment by D-Official** [comment]
Weird... I wouldn't know how to help with that, sorry :(
