### ISSUE TITLE
Unused Taunts Mod

### ISSUE THREAD

**Issue by Dededeez** [D-Official/PizzaTowerSwitch-FMOD#12]
There is an unused super taunt on the pizza tower wiki that I noticed isn't included in the unused taunts mod, would it be possible to add it in some time? If it's complicated to add in then it's not necessary, I was just curious if it would be possible to add it. ![Supertaunt.gif](https://github.com/D-Official/PizzaTowerSwitch-FMOD/assets/148832059/78149f64-209a-42c9-b95a-bb9e70461b57)

**Comment by D-Official** [comment]
It is possible and will be considered when the port needs to be updated again (to fix a game-breaking bug, or to update the Pizza Tower version)
