### ISSUE TITLE
Lap 3

### ISSUE THREAD

**Issue by Marezed** [D-Official/PizzaTowerSwitch-FMOD#16]
The lap 3 mod does not give enough time for war lap 3

**Comment by D-Official** [comment]
Does it not? I don't recall seeing any changes to the WAR timer from the Lap 3 mod.

See this video for example: https://youtu.be/T8ENVDHdy-s
There don't seem to be any changes to the timer, or layout, or any additional time monitors... The guy just goes very fast.
