### ISSUE TITLE
Add more custome palettes

### ISSUE THREAD

**Issue by ERWANDAWA** [D-Official/PizzaTowerSwitch-FMOD#19]
Would be cool for Sr6

**Comment by D-Official** [comment]
If you include any good ideas or colors in this issue I will consider them for the next release.

**Comment by ERWANDAWA** [comment]
Ok uhhm just a second

**Comment by ERWANDAWA** [comment]
Transparent skin
"Why are there floating clothes here

Transparent clothes
"I can see through you"

All transparent
"Where'd you go?"

More lgbtq+ flag colors

D pattern
"Praise D"

Piss yellow
"Piss"

The noise
"Something is wrong here"

Noisette pink
"I'd like a tip"

Gremlins paterns
"Why are noise and noisette on this?"

Old noise design
"I got a feeling of deja vu"

Burning rage
"Wow you're all red"

Grinch pallette
"Have I truly become a monster?"

Question mark pattern
"???"

That's all I can think of

**Comment by ERWANDAWA** [comment]
You don't have to add what you don't want it's just suggestions
