### ISSUE TITLE
Having issues getting decrypt.py to work

### ISSUE THREAD

**Issue by KirbyKing186** [D-Official/PizzaTowerSwitch-FMOD#20]
I have included decrypt.py, the encrypted SR 5 Fix 1 file, and my data.win file all in the same folder. I also installed Python 3.12. When I click decrypt.py, it opens and immediatley closes, with no files being changed.

The SHA-256 hash of my data.win is d77d34183aac40890373371e96bc3093f6c83d45a528dfe29cf900857c146303. Any fixes/solutions to this issue?

**Comment by lucasdaweb95** [comment]
my pc also froze every time i ran the script, i think a xdelta patch would work better.

**Comment by D-Official** [comment]
> I have included decrypt.py, the encrypted SR 5 Fix 1 file, and my data.win file all in the same folder. I also installed Python 3.12. When I click decrypt.py, it opens and immediatley closes, with no files being changed.
> 
> The SHA-256 hash of my data.win is d77d34183aac40890373371e96bc3093f6c83d45a528dfe29cf900857c146303. Any fixes/solutions to this issue?

Could you please run the decrypt.py in that folder from the Command Prompt? It should display a message if anything went wrong when ran from there. The hash is correct.

**Comment by D-Official** [comment]
Great!
