### ISSUE TITLE
The in-game Pause Menu does not freeze the level timer

### ISSUE THREAD

**Issue by KirbyKing186** [D-Official/PizzaTowerSwitch-FMOD#21]
In Pizza Tower SR 2, when you were in the pause menu, the level timer froze and unfroze when you got out of the menu. But in the latest revision (SR5 Fix 1), the level timer keeps going in the pause menu. As of now, the latest version of Pizza Tower freezes the timer when in the pause menu, so this is most likely a bug within the port.

**Comment by D-Official** [comment]
The behavior is consistent with the latest Pizza Tower version for me: the level timer pauses in the pause menu by default, keeps going if Speedrun Timer is enabled. Can you check if you happen to have it enabled on Switch?

**Comment by KirbyKing186** [comment]
Ah, I mistook that as a glitch when in reality I just changed the wrong setting. Thanks for correcting me!
