### ISSUE TITLE
The Nintendo logos do not display upon booting the game

### ISSUE THREAD

**Issue by KirbyKing186** [D-Official/PizzaTowerSwitch-FMOD#22]
Unlike other games on the switch, the latest Pizza Tower port (SR 5, Fix 1) does not display any Nintendo logos when clicking the game. Is this intentional to avoid any disputes with Nintendo?

**Comment by D-Official** [comment]
This is by mistake. It should actually display this:
![977004593689014272](https://github.com/D-Official/PizzaTowerSwitch-FMOD/assets/148906610/95aa4e17-4916-4bbe-a350-ae296bc94846)
But it looks like I've forgotten to do it for the last release...

**Comment by KirbyKing186** [comment]
Heyo! When booting the game (specifically SR 8), it displays “Licensed by (Trans Rights)” instead of just (Trans Rights). Was this intended?
