### ISSUE TITLE
Noise Update Progress

### ISSUE THREAD

**Issue by D-Official** [D-Official/PizzaTowerSwitch-FMOD#23]
The Noise Update will be brought to Switch. Please be patient as I enjoy the update and do other things people do in their lives, because I am an individual that exists out there. Can you find me? This update will find you.

Tasks left to do:
- [x] Port the thing
- [x] Uhh, maybe include #12

**Comment by KirbyKing186** [comment]
Take as much time as you nee, and good luck with porting it!

**Comment by lucasdaweb95** [comment]
how DARE you be a human being!!!n/j

**Comment by notChocoMilk** [comment]
holy crap, we'll be able to play as the yellow noid in pete's tower for the nintendo switch at some point

**Comment by Bossiskeyboard** [comment]
WAH

**Comment by XuWu36999** [comment]
How to unlock the game file without a computer💀

**Comment by lucasdaweb95** [comment]
> How to unlock the game file without a computer💀

use a tinfoil shop i guess

**Comment by notChocoMilk** [comment]
> How to unlock the game file without a computer💀

literally none of what you just said makes sense, and the skull emoji doesn't help either

**Comment by KirbyKing186** [comment]
> How to unlock the game file without a computer 💀

To legally install it, you need some device running Python and a legal copy of Pizza Tower update. Also, if you’re referring to the Noise Update, it hasnt been ported as of now.

**Comment by AndreAR22** [comment]
I think he was referring to the save data, how to modify it to 101% without a computer (i guess??)

**Comment by Giu001** [comment]
Take as much time as you need, your work is greatly appreciated!!! :)

**Comment by Wraiax** [comment]
What's the progress looking like?

**Comment by D-Official** [comment]
> What's the progress looking like?

I haven't gotten as much done as I wanted to due to several reasons. But among other things, I've completely rewritten the FMOD script included in this repository.

**Comment by HeadsetMan** [comment]
Oh boy, I can't wait to fight the Doise.

**Comment by D-Official** [comment]
At this stage nearly all the code and assets from the Noise update are inside the GameMaker project. I can play as him. But the "merging" has caused several regression bugs around every area the port has ever changed (to optimize, or to add new content like mods from the port menu).

Roughly, the tasks I have to do now are:
1. Fix decompilation/regression bugs by playing the game a lot (I have people helping me with this, don't worry)
2. Implement new FMOD events (all simple "play a sound" events have already been implemented, in the same manner as the base game, see the top of fmod.gml if you're curious)
3. Implement swap mode music changing (I have a pretty good plan on how)

I don't know how long it'll take me and I don't think I'll ever do something like this again. Like I mentioned in the other thread I have less free time and my interest in this game has lowered by a lot. But I do want to at least finish this.

**Comment by Wraiax** [comment]
Thanks for all your hard work, no matter how long this takes you man!

**Comment by D-Official** [comment]
Quick update. The port is playable start to finish. The part that needs most work is still the SFX. (there are still some FMOD events that are not implemented/not changed to account for the Noise). That, and also I haven't gotten to swap mode at all, but I imagine it won't be (that much) of an issue

**Comment by HeadsetMan** [comment]
The progress is taking a long time, but I will patiently await the release.

**Comment by D-Official** [comment]
I've been on a roll for the past few days. I do think I can say this: Do expect the update to release within a few days from now.

**Comment by Aitornado8** [comment]
I'm so hyped to play the update on Switch, I'm on my vacation and playing the port keeps me distracted. Thank you for your hard work:]

**Comment by D-Official** [comment]
Have fun!
