### ISSUE TITLE
2 Bugs

### ISSUE THREAD

**Issue by MatthewMerg** [D-Official/PizzaTowerSwitch-FMOD#24]
**Bug 1:**
In Peppibot Factory's lapping room, the background in incorrect, using a sprite of the Eggplantmobile instead of the regular background
![2024031420034800-E3BCD8C53331DF293E23E783D4F7C197](https://github.com/D-Official/PizzaTowerSwitch-FMOD/assets/151106609/745a0c61-0834-4a7b-a8d9-d09b80a2af9e)
**Bug 2:**
During the results screen after getting a P-Rank, the background will fade as the results are popping up.

https://github.com/D-Official/PizzaTowerSwitch-FMOD/assets/151106609/67775dd0-5000-48f0-8274-5341329100e6

**Comment by D-Official** [comment]
Can replicate both, thank you for opening this issue! Will be fixed for the next release.
