### ISSUE TITLE
Egg's Lap Mod

### ISSUE THREAD

**Issue by HeadsetMan** [D-Official/PizzaTowerSwitch-FMOD#27]
This Isn't Really A Issue, But Is It Possible To Add This Mod To The Port Menu?

**Comment by notChocoMilk** [comment]
already been requested before & if i recall correctly has been stated to not be happening. if the port is open-sourced one day, it would be pretty cool to see it added though

**Comment by HeadsetMan** [comment]
Thanks for letting me know.
