### ISSUE TITLE
Checkpoints for Lap 3

### ISSUE THREAD

**Issue by HeadsetMan** [D-Official/PizzaTowerSwitch-FMOD#28]
Could you please consider adding checkpoints for the third lap? It would be greatly appreciated as repeating the levels can be quite time-consuming. Thank you for your attention to this matter.

**Comment by D-Official** [comment]
I am going to stick to what the original lap 3 mod had - but you can still save some time if you want by using the console command `panic` when you start the level, which will make you go into Pizza Time immediately. If you then go to the lap portal you'll start at lap 2 and you'll have 1 lap to remove obstacles and whatnot before lap 3.

**Comment by HeadsetMan** [comment]
Thank you for informing me, and I appreciate your suggestion for potential checkpoints. Please disregard this message as I understand you are already diligently working on the noise update.
