### ISSUE TITLE
And how much longer to wait?

### ISSUE THREAD

**Issue by Proshit** [D-Official/PizzaTowerSwitch-FMOD#29]
Summer is coming soon, the end of spring. Everyone managed to play Noise Update, even bought it on Steam for the sake of it. And the port on the switch is still not out.. It's sad :(
Why you do update so long? Today, I hope that you will do it at least before the end of the year, because 5 months have passed since the beginning of the announcement of Noise Update, if not more. I apologize for writing questions about this. I can help with the beta text if necessary.

**Comment by Dededeez** [comment]
From what I know, porting is a complicated and tricky process, it takes a while, so just let them take as long as they need without rushing it. After all, we want it to be the best it can be. That being said though, I don't think an occasional progress update every once in a while would hurt either (once every 2 weeks possibly?) but that's entirely up to D, that's just a personal suggestion of mine.

**Comment by D-Official** [comment]
> Summer is coming soon, the end of spring. Everyone managed to play Noise Update, even bought it on Steam for the sake of it. And the port on the switch is still not out.. It's sad :( Why you do update so long? Today, I hope that you will do it at least before the end of the year, because 5 months have passed since the beginning of the announcement of Noise Update, if not more. I apologize for writing questions about this. I can help with the beta text if necessary.

I have less free time than I used to, and my interest in Pizza Tower has diminished. I think I would've been done way earlier if it weren't for those factors. I am still determined to finish it. 

> From what I know, porting is a complicated and tricky process, it takes a while, so just let them take as long as they need without rushing it. After all, we want it to be the best it can be. That being said though, I don't think an occasional progress update every once in a while would hurt either (once every 2 weeks possibly?) but that's entirely up to D, that's just a personal suggestion of mine.

I could write an update. Not biweekly, because the only thing that's going to change from this point is me fixing more bugs/polishing/improving the audio mixing. I guess I'll elaborate more on that in the [update issue](https://github.com/D-Official/PizzaTowerSwitch-FMOD/issues/23) soon.
