### ISSUE TITLE
Is it possible to mod the NSP?

### ISSUE THREAD

**Issue by scrap-hat** [D-Official/PizzaTowerSwitch-FMOD#3]
I wanna mod the nsp to port content from a pt mod called "pizza tower scoutdigo" but so far i got no luck. Any tips or maybe a possible port of said mod? is there another way i can contact you?

**Comment by D-Official** [comment]
The port, like the PC version, has a `.win` file (specifically named `game.win` for switch games). If you unpack the NSP you can then use UndertaleModTool to make changes to it like you would normally. (xdelta patches made for PC will not work on it)

Also, I know there's at least 1 person working on a port of that mod specifically. I don't know when they'll decide to release it.

My discord is `d_official`. It is not active, but I guess it could be used for conversation.

**Comment by scrap-hat** [comment]
i saw that by changing the .win file you can play other game maker games, i saw this method on gbatemp. could that be sone but with your port? do you know who's working on the scoutdigo port? id like to contact them

**Comment by Aitornado8** [comment]
In the case that someone wants to port mods that are other game versions (They have they're own save files, executable and that stuff) how do you compile the .nsp? Idk if you have the GameMaker subscription with the console exports but It would really help to know the method to export the nsp
