### ISSUE TITLE
Future plans after Noise Update

### ISSUE THREAD

**Issue by Dededeez** [D-Official/PizzaTowerSwitch-FMOD#30]
You have said that your interest in Pizza Tower has dropped recently, and that you don't have as much free time as you used to. Considering that, do you plan on dropping the port after this, passing it on to someone else, or anything else? I'm just curious to know if you have any ideas for what lies in the future for this port. Thank you in advance for your answer.

**Comment by D-Official** [comment]
After I'll release the update I think I'll only do any bugfix updates whenever any bugs come up here. 
As for passing the port's source code to someone else: The biggest obstacle to creating a port is FMOD, and I have already open sourced my GML replacement of it, and will open source my rewrite as well once the update is out. If anyone wants to do a port for later versions of the game this would help them immensely. But my port specifically will remain on life support for the foreseeable future, after the update.
