### ISSUE TITLE
Missing Song After Credits

### ISSUE THREAD

**Issue by Dededeez** [D-Official/PizzaTowerSwitch-FMOD#31]
I noticed that after the credits play, and leaving it on the end screen, the song Choosing the Toppings is supposed to play after funiculi holiday, and continue looping after it, but it doesn't in this port. I'm just letting you know this in case you didn't know already. Thank you in advance for your response, and best of luck on your work for the port.

**Comment by D-Official** [comment]
Actually didn't know that, seems to be true. Will be fixed in SR 6.
