### ISSUE TITLE
how do I use it

### ISSUE THREAD

**Issue by nolan540** [D-Official/PizzaTowerSwitch-FMOD#32]
I've tried connecting my PC and my switch with a USB charger so the port would get on there but that got me nowhere so yea

**Comment by nolan540** [comment]
![Screenshot 2024-07-18 5 13 21 PM](https://github.com/user-attachments/assets/449dbe21-6a48-4db6-a02b-0288aa516dae)

**Comment by Dededeez** [comment]
Did you already decrypt the .nsp using a Pizza Tower data.win? Once you do that, just use any .nsp installer, connect your switch to your device with the .nsp, and install the port.

**Comment by nolan540** [comment]
I'm using Chromebook if you couldn't tell

**Comment by Dededeez** [comment]
I haven't had success with a Chromebook unfortunately. Personally I transfer the decrypted nsp to my Android phone, then use NS-USBloader on it, then use Awoo Installer on my switch, and install over LAN or internet.

**Comment by KirbyKing186** [comment]
The decrypted NSP is fairly small (334MiB, less than half a gigabyte), so if you cant use USB installations, try adding the `.nsp` file to your switch wirelessly via FTP, by inserting the MicroSD card to the Chromebook, by possibly trying a different USB tool like Hekate UMS, etc.

**Comment by D-Official** [comment]
https://switch.hacks.guide/
