### ISSUE TITLE
Having issues decrypting file

### ISSUE THREAD

**Issue by Dededeez** [D-Official/PizzaTowerSwitch-FMOD#34]
Sorry to bother about this, but I have everything set up properly for the script to work, yet it keeps giving me the same error here. What exactly am I missing for this to work? Thanks in advance for help with this.
![Screenshot 2024-08-07 6 06 04 PM](https://github.com/user-attachments/assets/6cf541ca-9151-4e63-8eaf-7313e8c1d1c2)
![Screenshot 2024-08-07 6 06 43 PM](https://github.com/user-attachments/assets/226d1a28-eb4b-4ea5-9c7e-bc1b8414b156)

**Comment by D-Official** [comment]
Doesn't seem to be your fault. Can you add
```py
print(encrypted_path)
print(data_path)
```
to line 42 of the script, and see what it prints? Both should contain the full paths for the .bin and .win files.

**Comment by Dededeez** [comment]
This is what it shows
![Screenshot 2024-08-07 6 28 58 PM](https://github.com/user-attachments/assets/b54d8ebb-2364-4678-a8e1-ad5ed4284baa)

**Comment by D-Official** [comment]
If you have subfolders in the folder you're running the script in, it could be looking for files there as well (I should've probably written that it does that). But in case you don't, you can just manually supply both of these paths like so, by placing
```py
encrypted_path = "(full path to bin file)"
data_path = "(full path to data.win)"
```
in line 42.

**Comment by Dededeez** [comment]
I added those lines, and now it shows this when I try to run it. The folder I'm trying to run this in has nothing except the script, the .bin, and the .win file
![Screenshot 2024-08-07 6 35 24 PM](https://github.com/user-attachments/assets/68b05c40-81dd-467f-b53a-911376085f14)

**Comment by D-Official** [comment]
Sorry, I used the parentheses there as a placeholder. You are meant to replace them with the actual full path. Make sure the full path uses forward slashes.

**Comment by Dededeez** [comment]
This is what happened this time. 
![Screenshot 2024-08-07 6 53 44 PM](https://github.com/user-attachments/assets/2ef333ab-0cfc-465f-980b-4b9c1f52fe8a)

**Comment by D-Official** [comment]
You need quotes around the paths

**Comment by Dededeez** [comment]
I finally got it working now. Thank you very much for helping me.
