### ISSUE TITLE
Adding the NSP to Ghost shop

### ISSUE THREAD

**Issue by GalaKtu** [D-Official/PizzaTowerSwitch-FMOD#36]
I was wondering, since ghost shop is one of the only public shops that are still up and running, i was hoping you would post the update there. If you are going to, It would be deeply appreciated

**Comment by burnedpopcorn** [comment]
I extremely doubt he would, considering all the trouble he went through to encrypt the port in order to make sure everyone who can access it actually owns PT, which you can't verify on Ghost Shop
