### ISSUE TITLE
Text display bug

### ISSUE THREAD

**Issue by Wtfguvuhvyh** [D-Official/PizzaTowerSwitch-FMOD#37]
The font has been stretched, and the text is missing one line.
![Screenshot_2024-08-08-14-52-04-78_94e0515f7dafd9fd45b2c22cd58d3358](https://github.com/user-attachments/assets/b0d58b8b-9d2a-4af2-adfd-a131e17cc292)
![IMG_20240808_150251](https://github.com/user-attachments/assets/bec7f231-ca2a-4d90-a558-7cb1d79d41c2)

**Comment by D-Official** [comment]
This seems to be an emulator bug. It does not happen on my Switch.

**Comment by Wtfguvuhvyh** [comment]
Alright.
