### ISSUE TITLE
Small Audio Error

### ISSUE THREAD

**Issue by Dededeez** [D-Official/PizzaTowerSwitch-FMOD#38]
During the rocket ride transitions between planets on Deep-Dish 9 while playing as The Noise, occasionally it will play Peppino's scream instead. Here's a video with the error.

https://github.com/user-attachments/assets/8fa4d3ef-4f66-4861-a0b2-7a3ce5d15e6e

Also unrelated, I didn't want to make a new issue for this, but there is also no vibration in the controller when landing with The Noise's crusher jump. I don't know if this is intentional or not, but I just wanted to point that out in case it's an oversight.

**Comment by D-Official** [comment]
Will be fixed in SR 7.
Also, I tested and there's no vibration for the crusher in the PC game as well
