### ISSUE TITLE
Unsure of what to do, as I am a complete beginner in coding

### ISSUE THREAD

**Issue by Wraiax** [D-Official/PizzaTowerSwitch-FMOD#4]
I've never touched a line of code in my life, so I'm unsure of what to actually do

I've downloaded the SR 4 file from the Releases tab, and I have the data.win from PT, but I don't understand where I should put these files in Python, or how to use the decrypt.py script; I've looked online and found no success

So could you please make a detailed explanation of what exactly to do? And could you please make it as understandable as possible as I don't know anything about coding

Thanks in advance

**Comment by D-Official** [comment]
Sorry, I didn't write a very "noob friendly" guide, I kinda rushed it out.
Install the latest version of python from python.org, then place the script, the bin, and the data.win all in the same folder. Double click to run the script and it should create the NSP. (If that doesn't work, try opening command prompt, then type `cd (directory where the script is)` enter, then type `python decrypt.py`)

**Comment by Wraiax** [comment]
What do you mean by "place the script in a folder"?

Are you referring to some kind of file? Because until now it was just a command I was writing in Python

**Comment by D-Official** [comment]
You are meant to download the `decrypt.py` file and run it, in the same folder as where the .bin and data.win are, not paste it's contents into the python interpreter. Though I think that should work if you start python in that same folder.

**Comment by Wraiax** [comment]
So, I've downloaded decrypt.py from cryptopuck on here, and I put it in a folder with those two files, when I run it it opens python for a split second and then it closes; but it does nothing, what am I doing wrong?

**Comment by D-Official** [comment]
That is a different script. Go to this repository, download all of it as a zip by clicking the button left of the About section, and use the decrypt.py from the zip.

**Comment by Wraiax** [comment]
It ends by saying that there is a memory issue, what should I do?

**Comment by Wraiax** [comment]
And now it's just staying on "decrypting" and it just makes my pc lag a lot

**Comment by Wraiax** [comment]
Nvm it worked, thanks for the speed and the clarity
