### ISSUE TITLE
(Question) What Sounds go to Which Audio Group

### ISSUE THREAD

**Issue by burnedpopcorn** [D-Official/PizzaTowerSwitch-FMOD#41]
You mentioned that there are 3 audio groups that have to be used, but what sounds go to which audio groups? (especially audiogroup_special)

**Comment by D-Official** [comment]
I left a comment in fmod.gml for this:
```
In the port, SFX audio files are assigned to audiogroup_sfx, music audio files are assigned to audiogroup_default,
and audiogroup_special exists so John pillar's Meatphobia track can be turned up while the music is turned down. 
I don't remember why it's done like this, probably for a good reason.
```

**Comment by burnedpopcorn** [comment]
@D-Official 
Should specified

What was the file name for John Pillars Meatophobia track?

**Comment by D-Official** [comment]
mu_dungeondepth, the event is "event:/music/pillarmusic"

**Comment by burnedpopcorn** [comment]
Thanks

Also sorry for wasting more of your time
But last question

Is that the only track in audiogroup_special?

**Comment by D-Official** [comment]
Yes
