### ISSUE TITLE
List of bugs I noticed

### ISSUE THREAD

**Issue by Aitornado8** [D-Official/PizzaTowerSwitch-FMOD#42]
I'll update it as I find more, I'm trying to Holy Shit! the first Noise file.
1. The Noise's jump sound doesn't play, it plays Peppino's.
2. In Freezerator, the ice circle guys doesn't attack. I refer to that attack that launches some ice spines or something like that (idk if you know what I mean).
3. The second song of Peppibot Factory is in sync with the first one and the secrets (idk If it's just Peppibot or all the levels but just sayin')
4. I can't get the first secret achievement on Peppibot Factory.
5. I think that the escape music for Noise doesn't loop correctly (maybe I'm incorrect).
6. At the credits of Noise's campaign, it shows the Z key sprite. Again I just played the Noise's campaign.

Just finished it, amazing work of your part with the port.

**Comment by D-Official** [comment]
1, 2, and 4 have just been fixed, 3 is not a problem.
I actually forgot Noise had his own jump sound.

**Comment by Dededeez** [comment]
I would like to add that Gnome Forest is missing the tutorial sign when playing as The Noise

**Comment by Aitornado8** [comment]
Unrelated but I think I could be the first one to dun' it
![IMG_20240808_221226](https://github.com/user-attachments/assets/d4142bf3-3db5-422c-8eaa-35cbf602d419)

**Comment by D-Official** [comment]
Very cool!

> I would like to add that Gnome Forest is missing the tutorial sign when playing as The Noise

Fixed

**Comment by Aitornado8** [comment]
Btw I've updated the main message, again If I notice something else I'll say it.

Also, will you add more mods to the mods menu? Asking bc of curiosity

**Comment by D-Official** [comment]
5 - It loops correctly from my testing
6 - Fixed

> Also, will you add more mods to the mods menu? Asking bc of curiosity

Probably not.

**Comment by Dededeez** [comment]
This is entirely unnecessary to add, but there is an unused taunt for The Noise now. 
![Oh_no_not_noisette](https://github.com/user-attachments/assets/c63e5247-9ca4-47e4-9005-58507ab910d3)
Once again, you don't need to add it, but I do think that it's worth mentioning at the very least.

**Comment by D-Official** [comment]
I don't want to add this one since Noisette is a character that you can see in the hub, so it wouldn't make sense if a taunt made her appear twice.

**Comment by Aitornado8** [comment]
Other thing I noticed, the effect of Noise's tornado attack (those white lines around him) doesn't align correctly with the sprites. As I can't send a screenshot from my switch I did an example in case I explained badly
![Screenshot_2024-08-09-09-47-46-675-edit_jp ne ibis ibispaintx app](https://github.com/user-attachments/assets/9f6515ac-3edd-4df4-8883-232666247689)

**Comment by D-Official** [comment]
Fixed as well. I thought it was a bug in the PC version too, guess I was wrong
