### ISSUE TITLE
issue with installation

### ISSUE THREAD

**Issue by Wraiax** [D-Official/PizzaTowerSwitch-FMOD#43]
ive tried basically everything seen in the other issue about the installation, but now im faced with another problem
![Screenshot (12)](https://github.com/user-attachments/assets/c5976da8-c065-467f-ab86-a000f1c6cf5c)
what can i do to fix it?
thanks in advance

**Comment by D-Official** [comment]
Can you try running the script as administrator?

**Comment by Wraiax** [comment]
> Can you try running the script as administrator?

I don't know how to do that, my pc doesn't have that option

**Comment by Wraiax** [comment]
How do I enable it?

**Comment by Aitornado8** [comment]
Right click the script and in More Options (or smth like that) click Run As Administrator

**Comment by Wraiax** [comment]
> Right click the script and in More Options (or smth like that) click Run As Administrator

It specifically doesn't let me open that file as an administrator, however I am able to open python as an administrator, what do I do from here?

**Comment by Wraiax** [comment]
I also can't downgrade to windows 10 nor do I have access to a windows 10 pc

**Comment by Wraiax** [comment]
What can I do from here on? I'm really blocked rn since I can't really do anything, if I send you my data file can you send me the nsp? Just so I can prove its mine?

**Comment by D-Official** [comment]
Try running command prompt as administrator, then typing cd and write the directory where you have the script and the .win and .bin files, and then write the name of the script and press enter

**Comment by Dom-Juan** [comment]
1. Open your terminal as administrator (click on Search, write terminal, right click and run as administrator).
2. write on the terminal: cd "C:\Users\User\Downloads\PizzaTowerSwitch-FMOD-main". Where user is your current user username, mine is Magoimortal so it is "C:\Users\Magoimortal\Downloads\PizzaTowerSwitch-FMOD-main", dont copy the dot, only from cd to the last ".
3. Copy data.win to the folder as said in the tutorial.
4. write on the terminal python decrypt.py

This should decrypt with admin privileges.

**Comment by Wraiax** [comment]
It says the directory name is invalid

**Comment by Dom-Juan** [comment]
![image](https://github.com/user-attachments/assets/c35dd799-3291-4cb7-b827-013d6ddb7ec0)

You need to download the full folder and extract it just like the picture, put the data.wim inside there and follow the stuff i wrote.

**Comment by Dom-Juan** [comment]
![image](https://github.com/user-attachments/assets/71355041-407e-4d0b-b9b4-6b3711755e09)
Inside should look like above my pick after you copy the data.win, then you get inside the folder with the admin priviledge terminal just like i told you and you can start the decrypt.

**Comment by Wraiax** [comment]
> ![image](https://private-user-images.githubusercontent.com/35587574/356399360-71355041-407e-4d0b-b9b4-6b3711755e09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNTU4NTMsIm5iZiI6MTcyMzE1NTU1MywicGF0aCI6Ii8zNTU4NzU3NC8zNTYzOTkzNjAtNzEzNTUwNDEtNDA3ZS00ZDBiLWI5YjQtNmIzNzExNzU1ZTA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDIyMTkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5MzRjMWZlMDEwNDQ3ZDllNmY3OGY3MzQ3ZDI5MTIzZmRhNGMwMzUzYjdhZGE2M2YyNDY2YTVlYmY2ZmVkODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GkY8wF_Vby3cCRuu4bxTmQPWr7dx3v6dvz7UcU9Pr74) Inside should look like above my pic after you copy the data.win, then you get inside the folder with the admin priviledge terminal just like i told you and you can start the decrypt.

![Screenshot (13)](https://github.com/user-attachments/assets/128134c5-f8af-4651-908d-6d7ca7d1d977)
like this?

**Comment by Dom-Juan** [comment]
you need to input 1 command at time

So first its cd "C:\Users\angel\Downloads\PizzaTowerSwitch-FMOD-man" then you write python decrypt.py

**Comment by Wraiax** [comment]
> you need to input 1 command at time
> 
> So first its cd "C:\Users\angel\Downloads\PizzaTowerSwitch-FMOD-man" then you write python decrypt.py

ok so i click enter on the first one and then after that the second one?

**Comment by Dom-Juan** [comment]
> > you need to input 1 command at time
> > So first its cd "C:\Users\angel\Downloads\PizzaTowerSwitch-FMOD-man" then you write python decrypt.py
> 
> ok so i click enter on the first one and then after that the second one?
Yep, press enter on the first one, it will change folders then you input the second one and press enter again.

**Comment by Wraiax** [comment]
It says python was not found, weird since I do have python installed and used it before to open the program normally

**Comment by Dom-Juan** [comment]
Try: py decrypt.py


Sometimes python will shortcut the execution to python or just py.

**Comment by Wraiax** [comment]
Thanks, it worked!

**Comment by Dom-Juan** [comment]
You're welcome!

![image](https://github.com/user-attachments/assets/6ab9f8a0-b677-4997-bdd3-ccbb8ef3a115)
