### ISSUE TITLE
The font position has shifted a bit.

### ISSUE THREAD

**Issue by Wtfguvuhvyh** [D-Official/PizzaTowerSwitch-FMOD#44]
This bug is strange,and it's very small.
![IMG_20240809_092649](https://github.com/user-attachments/assets/79e088c5-9118-4f8f-a6a1-b8fa8eb20f4a)
![IMG_20240809_092615](https://github.com/user-attachments/assets/8c944fe3-3751-43a7-9d1b-0d77c11ed573)
![IMG_20240809_092541](https://github.com/user-attachments/assets/8b540010-ab35-4a49-940c-7a8318443f64)

**Comment by burnedpopcorn** [comment]
although I dont know much, I've heard that an updated GMS2 Runtime, which D has said that he did use, can cause this, so i'm not really surprised

**Comment by D-Official** [comment]
Fixed. Wasn't a runtime issue (runtime didn't change between SR 5 and 6), my scr_text_util file was just outdated.
