### ISSUE TITLE
Noise lap 3 question

### ISSUE THREAD

**Issue by Dededeez** [D-Official/PizzaTowerSwitch-FMOD#45]
I've gotten a lap 3 with The Noise, and noticed that he doesn't have a unique results screen animation for it like Peppino does. Is this intentional? Thank you in advance for your response.

**Comment by Aitornado8** [comment]
I guess that it's because the og lap 3 mod (which is the one used on the port) hasn't been updated for a long time, and with that, it doesn't have any Noise related things.

**Comment by D-Official** [comment]
I did find a screen I could use for him, but I didn't understand who exactly made it, and I want to give proper credit. So he just doesn't have a screen.

**Comment by Aitornado8** [comment]
One last thing (i don't want to be annoying) but I could make a lap 3 Noise rank screen for the port if you want
