### ISSUE TITLE
Re-implementing Issue

### ISSUE THREAD

**Issue by burnedpopcorn** [D-Official/PizzaTowerSwitch-FMOD#46]
So my dumbass is back here

and what I've done is extract the sounds from your Switch Port, import said sounds and the PUBLIC ```fmod.gml``` file into GMS2 (2023.2), and put all sounds into their respective audio groups

but when the game loads, and when you press Z to skip the Intro (or if it finishes) the game gets stuck indefinitely
what happens is that ```obj_loadingscreen``` gets all the way to Alarm 1, where it's supposed to alternate between calling Draw and Alarm 1 events repeatedly, until all textures load, and it can proceed to loading the next room

but for me, it calls Alarm 1 once (and loads one single texture), and stalls there indefinitely

and this is an issue with ```fmod.gml```, as without it, the game loads fine
so is there any way you can help, or is there something I missed when importing this?

> also i did not meaningfully modify obj_loadingscreen or fmod.gml
>
> also I used loypoll's decomp as a base

**Comment by D-Official** [comment]
I'm not sure what you mean by stall there. Try following what it does with the debugger.
If something is making obj_loadingscreen not run the alarm again you'll find it pretty quickly with the amount of instances that exist at that phase.

**Comment by burnedpopcorn** [comment]
I say stall, as the game doesn't proceed further, but the game doesn't crash either, so I never get an error

But I'll use the debugger and see what that tells me

**Comment by burnedpopcorn** [comment]
nevermind

appearently, it was the fact the ```add_music``` for the MainMenu sound was still in ```obj_music```
my bad

but now pausing has the same issue...
