### ISSUE TITLE
New running lap

### ISSUE THREAD

**Issue by ejsiz** [D-Official/PizzaTowerSwitch-FMOD#47]
Can I have a new lap?

**Comment by D-Official** [comment]
No

**Comment by ejsiz** [comment]
> 不



> 不

Why? I don't understand

**Comment by D-Official** [comment]
> > 不
> 
> > 不
> 
> Why? I don't understand

I don't want to implement more laps

**Comment by ejsiz** [comment]
> > > 不
> > 
> > 
> > > 不
> > 
> > 
> > 为什么？我不明白
> 
> 我不想实施更多的圈数

LAP4？
