### ISSUE TITLE
More mods?

### ISSUE THREAD

**Issue by Wtfguvuhvyh** [D-Official/PizzaTowerSwitch-FMOD#48]
1.Can you add a checkpoint for lap3?
2.Can you add two options in mods to choose between attack and side attack? Just like Scoutdigo.
3.Can you add a key in swap mode to make the pep and noise roll? This feature usually requires connecting a controller and a keyboard in the PC version, and both pressing the dash key to trigger it.

**Comment by Dededeez** [comment]
D has already mentioned they won't be adding checkpoints to lap 3 here #28.

**Comment by D-Official** [comment]
I won't be adding any more mods
