### ISSUE TITLE
Issues with obtaining Noise clothes

### ISSUE THREAD

**Issue by Dededeez** [D-Official/PizzaTowerSwitch-FMOD#51]
The Halloween clothes seem to be unobtainable with The Noise. I collected 5 pumpkins as him, and I didn't get the Candy Wrapper clothes, so I'm assuming that the rest of the Halloween clothes may behave similarly. Also I believe the Bubbly clothes may be unobtainable too, the one obtained from using all the Olive Bubbles in Deep-Dish 9. I would also want to verify if the Tower Guy clothes are obtainable too, but I haven't gotten to doing that yet.

**Comment by D-Official** [comment]
This seems to be my fault; The Halloween clothes aren't even wearable in SR 7. It's not unlocking because you've most likely already unlocked it with Peppino (Clothes are save-independent). Do let me know if the other clothes you mentioned are unobtainable. I took a look and nothing seems wrong about them at a glance.

**Comment by Dededeez** [comment]
I can confirm that Bubbly and Tower Guy do work. I was unsure about them, since Tower Guy is kind of finicky sometimes with the unlock method, and it turned out I was just missing one of the bubbles for Bubbly. But yes, the Halloween ones don't work.

**Comment by Dededeez** [comment]
Actually, I just found another bug. When playing swap mode as Peppino, he will have The Noise's scream when falling on lava in Bloodsauce Dungeon or when getting hit by a torch in Fun Farm.

**Comment by D-Official** [comment]
I have fixed both bugs, but I'll be waiting a little bit before doing another release, just in case more bugs are found.

**Comment by Dededeez** [comment]
I'll add this here, I'm not exactly sure what triggered it, but the music completely cut out during phase 2 of the final boss here. I've had other oddities with it, such as hearing the beginning that's normally only heard when playing unexpectancy part 2 in the sound test room, but I have had it completely cut out twice. I've included a clip with it happening in case it helps identify the issue.

https://github.com/user-attachments/assets/9420ce2b-bf14-4efa-932f-2ae2d4066f70

**Comment by D-Official** [comment]
These are the worst type of bugs... There seems to be absolutely no reason for this to happen. This clip was recorded on SR 7, right?

**Comment by Dededeez** [comment]
Yeah, this was SR 7. I had a feeling that it was a tricky one since it didn't seem like anything specific caused that to happen.
