### ISSUE TITLE
Question about the porting

### ISSUE THREAD

**Issue by Aitornado8** [D-Official/PizzaTowerSwitch-FMOD#54]
I don't wanna be annoying with opening issues, but which version of GameMaker did you used to make the .nsp or the encrypted files?
Asking cause I planned to make a custom version of it with more mods and stuff, like replacing Lap 3 mod for a more complete lapping one.
If you can tell me it would be very cool, cause Ik you said that you won't add more mods but there are some that I think that would be nice as more unofficial content (like lapping).

**Comment by D-Official** [comment]
If you want to mod the port, you'd need to use UndertaleModTool, modifying the game.win file by unpacking and repacking the NSP (I'm not really sure how to do this, but it is possible).

I can help you with the encryption though. This is the Python script I wrote to do it:
```py
def read_file_as_bytes(file_path):
    with open(file_path, 'rb') as file:
        return bytearray(file.read())
        
def duplicate_list_until_length_matches(original_list, target_length):
    result_list = original_list.copy()
    while len(result_list) < target_length:
        result_list += original_list
    return result_list[:target_length]
        
nsp_path = '05000FD261232000.nsp'
data_path = 'data.win'

print("Reading files")

nsp_bytes = read_file_as_bytes(nsp_path)
data_bytes = read_file_as_bytes(data_path)[::2]

data_big = duplicate_list_until_length_matches(data_bytes, len(nsp_bytes))

print("Encrypting")

encrypted_bytes = [byte1 ^ byte2 for byte1, byte2 in zip(nsp_bytes, data_big)]

print("Saving .bin")

with open("ENCRYPTED_SR_WHATEVER.bin", 'wb') as file:
    file.write(bytes(encrypted_bytes))

print("Done!")
```
the NSP must be named 05000FD261232000.nsp, and the data.win that should later be used to decrypt the file should be named data.win.
