### ISSUE TITLE
(Play as noise)After being defeated by Pizzaface Boss Fight, Pizzahead's body didn't turn black and emit smoke.

### ISSUE THREAD

**Issue by Wtfguvuhvyh** [D-Official/PizzaTowerSwitch-FMOD#55]
Here is the photo about this bug.
![Screenshot_2024-08-14-11-01-27-28_94e0515f7dafd9fd45b2c22cd58d3358](https://github.com/user-attachments/assets/3accca3f-d923-40be-a77d-fa168d07a91b)

**Comment by D-Official** [comment]
Thanks, will be fixed in SR 8
