### ISSUE TITLE
In level Gmone forest, goblin will not shoot arrows at players

### ISSUE THREAD

**Issue by Ldream114514** [D-Official/PizzaTowerSwitch-FMOD#56]
Here is the video about this bug.

https://github.com/user-attachments/assets/0cdb5e64-3297-416a-9a45-e468deb287f5

**Comment by Wtfguvuhvyh** [comment]
Yeah, he's right, this bug also means that Gnome Forest's Bullseye achievement can't be unlocked.

**Comment by D-Official** [comment]
Fixed in SR 8
