### ISSUE TITLE
The Noise’s jump sound effect doesn’t scale in volume with the in-game SFX slider

### ISSUE THREAD

**Issue by KirbyKing186** [D-Official/PizzaTowerSwitch-FMOD#57]
The SFX slider in the Audio menu of Pizza Tower SR 8 doesn’t change the volume of The Noise’s recently-added jump sound. Below is a video showing the potential issue:

https://github.com/user-attachments/assets/53ec9371-8c63-48f1-a925-ef1cd36201b8

**Comment by Wtfguvuhvyh** [comment]
The jumping sound effect of Noise does not scale with the volume of the SFX slider in the game, but it scales with the volume of the MUSIC slider in the game, and its audio adjustment is incorrectly reversed.

**Comment by D-Official** [comment]
I'm surprised I missed this, will be fixed for the next release.
