### ISSUE TITLE
In level the secret of world,Title card is not noise's cry

### ISSUE THREAD

**Issue by Ldream114514** [D-Official/PizzaTowerSwitch-FMOD#58]
Here is the video about this bug.

https://github.com/user-attachments/assets/c3b6ad5e-717b-4851-9b16-f89101531289

**Comment by Wtfguvuhvyh** [comment]
The music produced by the SOTW level title should have been composed of some Noise's 'WaWa' sounds like other level titles, but it did not.

**Comment by D-Official** [comment]
Will be fixed in the next release.
