### ISSUE TITLE
just needed to contact D

### ISSUE THREAD

**Issue by 123GiftedKnife** [D-Official/PizzaTowerSwitch-FMOD#59]
didnt have any other way of contact, just needed to see if theres any way i could get the nsp other than python. i can prove i own the game.

**Comment by D-Official** [comment]
I have no methods of sending the NSP. You need to use the Python script.

**Comment by 123GiftedKnife** [comment]
> I have no method of sending the NSP. You need to use the Python script.

do you know of any way to extract it on a mobile device?

**Comment by D-Official** [comment]
I'm fairly sure there are Python interpreters for Android, but I don't have any experience with them. There's nothing particularly OS exclusive about the script so it could likely work.

**Comment by D-Official** [comment]
Though that might be a bit problematic, since I'm assuming you have absolutely no way to access any computer to download the game files, and the data.win is a requirement for the script. If that's the case I can't really help you.
