### ISSUE TITLE
Improper music loop during final boss

### ISSUE THREAD

**Issue by Dededeez** [D-Official/PizzaTowerSwitch-FMOD#60]
It seems the music during phase 3 of the final boss loops at the wrong point. I noticed it happened with both Peppino and The Noise. I included a video of it happening with Peppino here. 

https://github.com/user-attachments/assets/a3db1e95-c1c8-4290-8e38-08420716c9d9

**Comment by D-Official** [comment]
I think the bug in question might be in GameMaker itself - I saw some pretty unexplainable behavior when debugging this last time. I'll have another look.
