### ISSUE TITLE
NSP file wont show up after decrypting

### ISSUE THREAD

**Issue by RecovrGav** [D-Official/PizzaTowerSwitch-FMOD#63]
I swear to god I own the game on steam but whenever I run the .py file in a folder with the .bin and data.win it always says 

"make sure the folder this script is ran in has exactly one .bin and exactly one .win file. (will not work if there's two of the same extension, because I don't know which one you want!)"

And after that message appears if I right click on the python window it prints the file path to the original data.win file from pizza tower for some reason. 
C:\Program Files (x86)\Steam\steamapps\common\Pizza Tower\data.win

I might be really stupid, but I have spent hours by now trying to do the same thing over and over and expecting a different result.
Help me.

**Comment by Dededeez** [comment]
I had a similar issue before actually, read through #34, that may help you

**Comment by RecovrGav** [comment]
> I had a similar issue before actually, read through #34, that may help you

The script works now, But I cant find the nsp file anywhere

**Comment by Dededeez** [comment]
It should just be in the same place you ran the script in I believe? I didn't have any issues after that, so I can't really help much outside of that.

**Comment by RecovrGav** [comment]
> It should just be in the same place you ran the script in I believe? I didn't have any issues after that, so I can't really help much outside of that.

thats ok, thanks for helping
