### ISSUE TITLE
Missing song during Pizza Time

### ISSUE THREAD

**Issue by Dededeez** [D-Official/PizzaTowerSwitch-FMOD#64]
The lap 2 theme is supposed to play during Pizza Time on the first lap if you run out of time and around 30 seconds pass with Pizzaface chasing you. I don't believe it does this in the port.

**Comment by D-Official** [comment]
I'm not going to recreate this in the port. It's an incredibly rare situation/condition that you have to trigger on purpose, doesn't really add anything, and I have a reason to believe it's unintentional.
