### ISSUE TITLE
Can't decode .bin file

### ISSUE THREAD

**Issue by Hargey-boop** [D-Official/PizzaTowerSwitch-FMOD#65]
Hi, I'm unable to decode the .bin file.

Process:
Placed data.win, ENCRYPTED_SR_8_FOR_V1.1.063_DATA.bin, decrypt.py in a folder with no other files
Ran decrypt.py by double clicking on file
Command window opens and closes with no files being generated

Attempted fixes:
Running from IDLE with Python 2.7.15: 
Error with syntax (Highlighting final " on line " with open(f"Pizza Tower SR {sr_number} [05000FD261232000][v0].nsp", 'wb') as file: ")

Running from IDLE with Python 3.7.1: 
Traceback (most recent call last):
  File "C:\Users\[Redacted]\Desktop\New folder (2)\decrypt.py", line 57, in <module>
    data_big = duplicate_list_until_length_matches(data_bytes, len(encrypted_bytes))
  File "C:\Users\[Redacted]\Desktop\New folder (2)\decrypt.py", line 37, in duplicate_list_until_length_matches
    result_list += original_list
MemoryError

Environment:
OS Name	Microsoft Windows 10 Pro
Version	10.0.19045 Build 19045
Processor	Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz, 3201 Mhz, 4 Core(s), 4 Logical Processor(s)
Installed Physical Memory (RAM)	16.0 GB

Let me know if you need any more info, thank you.

**Comment by D-Official** [comment]
I don't know why this would happen. The error suggests you're running out of memory, but the script should only need about less than a gigabyte of RAM to execute.

**Comment by Hargey-boop** [comment]
10.3 out of 16GB currently in use according to Task Manager.

**Comment by Hargey-boop** [comment]
Resolved by updating Python from 3.7 to 3.12.
