### ISSUE TITLE
After SUCCESSFULLY decrypting, .nsp file does not appear anywhere

### ISSUE THREAD

**Issue by RecovrGav** [D-Official/PizzaTowerSwitch-FMOD#66]
This is different from the last issue that I made, where the script does not work at all. Now, after the python window says "done" and it closes, the .nsp file is nowhere to be found. I don't have any more info on what happens, but I have been trying to decrypt this file for over a day now and I am losing my mind.

**Comment by D-Official** [comment]
Perhaps it has been saved to C:/ if it hasn't been saved to the folder where you ran it from. Otherwise, you can modify line 65 of the script to include your full directory, like
`with open(f"C:/path/to/your/directory/Pizza Tower SR {sr_number} [05000FD261232000][v0].nsp", 'wb') as file:`

**Comment by RecovrGav** [comment]
> Perhaps it has been saved to C:/ if it hasn't been saved to the folder where you ran it from. Otherwise, you can modify line 65 of the script to include your full directory, like `with open(f"C:/path/to/your/directory/Pizza Tower SR {sr_number} [05000FD261232000][v0].nsp", 'wb') as file:`

OMG TYSM IT WORKED
